root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorials/installation: introduction/installation.md
  integrations/programmatic-clients: reference/sql/supported-clients/clients.md
  getting-started/dolthub: concepts/dolthub/README.md
  bounties/bounties: introduction/getting-started/data-bounties.md
