root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorials/installation: ./getting-started/installation.md
  tutorials/reading-from-dolt: ./getting-started/reading-from-dolt.md
  tutorials/writing-to-dolt: ./getting-started/writing-to-dolt.md
  tutorials/using-sql: ./getting-started/using-sql.md
  tutorials/dolthub: ./getting-started/dolthub.md
  integrations/programmatic-clients: ./integrations/sql-clients.md
  getting-started/dolthub: ./dolthub/getting-started.md
  bounties/bounties: dolthub/bounties.md
  reference/sql/benchmarks: introduction/why-dolt/performance-characteristics
  introduction/why-dolt/characteristics: reference/characteristics.md
  reference/sql: interfaces/sql
  reference/sql/sql-support: interfaces/sql/sql-support/README.md
  reference/sql/sql-support/data-description.md: interfaces/sql/sql-support/data-description.md
  reference/sql/sql-support/expressions-functions-operators.md: interfaces/sql/sql-support/expressions-functions-operators.md
  reference/sql/sql-support/supported-statements.md: interfaces/sql/sql-support/supported-statements.md
  reference/sql/sql-support/miscellaneous.md: interfaces/sql/sql-support/miscellaneous.md
  reference/sql/dolt-sql-functions.md: interfaces/sql/dolt-sql-functions.md
  reference/sql/dolt-system-tables.md: interfaces/sql/dolt-system-tables.md
  reference/cli.md: interfaces/cli.md
  reference/python.md: interfaces/python.md
  integrations/sql-clients: interfaces/sql/clients.md
  getting-started/reading-from-dolt: getting-started/reading.md
  getting-started/writing-to-dolt: getting-started/writing.md
  getting-started/using-sql: getting-started/sql.md
