name: Open update docs PR

on:
  repository_dispatch:
    types: [ open-update-pr ]

jobs:
  get-results:
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gitbook-dev
          token: ${{ secrets.REPO_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
     - name: pull-request
       uses: repo-sync/pull-request@v2
       with:
         source_branch: ${{ github.event.client_payload.source_branch }}
         destination_branch: ${{ github.event.client_payload.destination_branch }}
         github_token: ${{ secrets.REPO_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
         pr_title: ${{ github.event.client_payload.title }}
         pr_assignee: ${{ github.event.client_payload.assignee }}
